default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: udeme_development
test:
  <<: *default
  database: udeme_test


production:
  <<: *default
  database: udeme_production
  username: app
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>