version: '3.4'
services:
  db:
    image: postgres:alpine
    container_name: app_db

  redis:
    image: 'redis:3.2.11-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  backend:
    build: ./backend
    container_name: app_backend
    command: bundle exec rails s -b 0.0.0.0 -p 3000
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
      - bundle:/usr/local/bundle
      - db_data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    container_name: app_frontend
    command: bundle exec rails s -b 0.0.0.0 -p 4000
    ports:
      - '4000:4000'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - bundle:/usr/local/bundle

volumes:
  db_data:
  bundle:
  redis: